{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cmind.fullname" . }}-secrets
  labels:
    {{- include "cmind.labels" . | nindent 4 }}
type: Opaque
stringData:
  PG_PASSWORD: {{ .Values.secrets.pgPassword | quote }}
  OWNER_EMAIL: {{ .Values.secrets.ownerEmail | quote }}
  OWNER_PASSWORD: {{ .Values.secrets.ownerPassword | quote }}
  DISCOVERY_JOIN_TOKEN: {{ .Values.secrets.discoveryJoinToken | quote }}
  DATA_PROTECTION_CERT_B64: {{ .Values.secrets.dataProtectionCertBase64 | quote }}
  DATA_PROTECTION_CERT_PASSWORD: {{ .Values.secrets.dataProtectionCertPassword | quote }}
{{- end }}
