// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260711103620_CopyExecutionJitter")]
    partial class CopyExecutionJitter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.AgentMandate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Autonomy")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("BacktestSettingsJson")
                        .HasColumnType("text");

                    b.Property<Guid>("CBotId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DockerImageTag")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("MaxDrawdownPercent")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<double>("RiskPercentPerTrade")
                        .HasColumnType("double precision");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Timeframe")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid?>("TradingAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CBotId");

                    b.HasIndex("TradingAccountId");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("AgentMandates");
                });

            modelBuilder.Entity("Core.AgentProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedInstanceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedParamSetId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DecidedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("MandateId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProposedName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Reasoning")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MandateId", "CreatedAt");

                    b.ToTable("AgentProposals");
                });

            modelBuilder.Entity("Core.AlertEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Acknowledged")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RuleId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("AlertEvents");
                });

            modelBuilder.Entity("Core.AlertRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<int>("IntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastEvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("AlertRules");
                });

            modelBuilder.Entity("Core.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("Core.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLockedOut")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MfaEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("MfaSecret")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<byte[]>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Role").HasValue("AppUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Core.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("text");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Hash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("PrevHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId");

                    b.HasIndex("UserId", "Time");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Core.CBot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("EncryptedAlgo")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("SourceProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SourceProjectId");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("CBots");
                });

            modelBuilder.Entity("Core.CBotSourceProject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("EncryptedProjectFiles")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<DateTimeOffset?>("LastBuildAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastBuildLog")
                        .HasColumnType("text");

                    b.Property<bool>("LastBuildSucceeded")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("CBotSourceProjects");

                    b.HasDiscriminator<string>("Language").HasValue("CBotSourceProject");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Core.CTraderIdAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CtidUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("EncryptedPassword")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Username")
                        .IsUnique();

                    b.ToTable("CTids");
                });

            modelBuilder.Entity("Core.ConsentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DocumentType", "Version");

                    b.ToTable("ConsentRecords");
                });

            modelBuilder.Entity("Core.CopyDestination", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AccountProtectionMode")
                        .HasColumnType("integer");

                    b.Property<double>("AccountProtectionStopEquity")
                        .HasColumnType("double precision");

                    b.Property<double?>("AccountProtectionTakeEquity")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("ConfigLockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("ConsistencyThresholdPercent")
                        .HasColumnType("double precision");

                    b.Property<bool>("CopyMasterSlippage")
                        .HasColumnType("boolean");

                    b.Property<int>("CopyOrderTypes")
                        .HasColumnType("integer");

                    b.Property<bool>("CopyPendingExpiry")
                        .HasColumnType("boolean");

                    b.Property<bool>("CopyPendingOrders")
                        .HasColumnType("boolean");

                    b.Property<bool>("CopyStopLoss")
                        .HasColumnType("boolean");

                    b.Property<bool>("CopyTakeProfit")
                        .HasColumnType("boolean");

                    b.Property<bool>("CopyTrailingStop")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DailyLossLimit")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DestinationAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("ExecutionJitterMaxMs")
                        .HasColumnType("integer");

                    b.Property<bool>("ForceMinLot")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<double>("LotSanityAbsoluteMaxLots")
                        .HasColumnType("double precision");

                    b.Property<double>("LotSanityMasterMultiple")
                        .HasColumnType("double precision");

                    b.Property<bool>("ManageOnly")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxDelaySeconds")
                        .HasColumnType("integer");

                    b.Property<double>("MaxDrawdownPercent")
                        .HasColumnType("double precision");

                    b.Property<double>("MaxLot")
                        .HasColumnType("double precision");

                    b.Property<double>("MinLot")
                        .HasColumnType("double precision");

                    b.Property<bool>("MirrorPartialClose")
                        .HasColumnType("boolean");

                    b.Property<bool>("MirrorScaleIn")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<double>("PropRuleDailyLossCap")
                        .HasColumnType("double precision");

                    b.Property<double>("PropRuleTrailingDrawdown")
                        .HasColumnType("double precision");

                    b.Property<bool>("Reverse")
                        .HasColumnType("boolean");

                    b.Property<string>("RiskMode")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<double>("RiskParameter")
                        .HasColumnType("double precision");

                    b.Property<double>("SlippagePips")
                        .HasColumnType("double precision");

                    b.Property<string>("SourceLabelFilter")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SymbolFilterMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool>("SyncClosedOnStart")
                        .HasColumnType("boolean");

                    b.Property<bool>("SyncOpenOnStart")
                        .HasColumnType("boolean");

                    b.Property<int>("TradingHoursEndMinuteUtc")
                        .HasColumnType("integer");

                    b.Property<int>("TradingHoursStartMinuteUtc")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "DestinationAccountId")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("CopyDestinations");
                });

            modelBuilder.Entity("Core.CopyProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedNode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("SourceAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("CopyProfiles");
                });

            modelBuilder.Entity("Core.Instance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CBotId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataDirSubPath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DockerImageTag")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<Guid?>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParamSetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Symbol")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Timeframe")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid?>("TradingAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CBotId");

                    b.HasIndex("NodeId");

                    b.HasIndex("ParamSetId");

                    b.HasIndex("TradingAccountId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("Instances");

                    b.HasDiscriminator<string>("Kind").HasValue("Instance");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Core.InstanceLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Line")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Stream")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId", "Time");

                    b.ToTable("InstanceLogs");
                });

            modelBuilder.Entity("Core.LegalDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("Published")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Version")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("LegalDocuments");
                });

            modelBuilder.Entity("Core.McpApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("KeyPrefix")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("McpApiKeys");
                });

            modelBuilder.Entity("Core.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataDirPath")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<int>("MaxInstances")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Nodes");

                    b.HasDiscriminator<string>("Kind").HasValue("Node");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Core.NodeStats", b =>
                {
                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<int>("BacktestCount")
                        .HasColumnType("integer");

                    b.Property<long>("BacktestDataUsedBytes")
                        .HasColumnType("bigint");

                    b.Property<double>("CpuPercent")
                        .HasColumnType("double precision");

                    b.Property<long>("DiskTotalBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("DiskUsedBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("MemTotalBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("MemUsedBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("RunningCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("NodeId");

                    b.ToTable("NodeStats");
                });

            modelBuilder.Entity("Core.OpenApiApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("EncryptedClientSecret")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RedirectUri")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("OpenApiApplications");
                });

            modelBuilder.Entity("Core.OpenApiAuthorization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AccessTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CtidUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("EncryptedAccessToken")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("EncryptedRefreshToken")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastRefreshedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RefreshFailedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long>("TokenVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("UserId", "CtidUserId")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("OpenApiAuthorizations");
                });

            modelBuilder.Entity("Core.ParamSet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CBotId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("JsonContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CBotId", "Name")
                        .IsUnique();

                    b.ToTable("ParamSets");
                });

            modelBuilder.Entity("Core.PropFirmChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowNewsTrading")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowWeekendHolding")
                        .HasColumnType("boolean");

                    b.Property<string>("AssignedNode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Breach")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<double?>("ConsistencyMaxDayProfitSharePercent")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("numeric");

                    b.Property<DateOnly?>("CurrentDay")
                        .HasColumnType("date");

                    b.Property<decimal>("CurrentEquity")
                        .HasColumnType("numeric");

                    b.Property<string>("DailyLossBasis")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<decimal>("DailyStartBalance")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DailyStartEquity")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DrawdownMode")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<double>("DrawdownWarnThresholdPercent")
                        .HasColumnType("double precision");

                    b.Property<bool>("DrawdownWarned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset?>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastEquityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MaxCalendarDays")
                        .HasColumnType("integer");

                    b.Property<double>("MaxDailyLossPercent")
                        .HasColumnType("double precision");

                    b.Property<int?>("MaxInactivityDays")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxOpenPositions")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaxSingleDayProfit")
                        .HasColumnType("numeric");

                    b.Property<double>("MaxTotalDrawdownPercent")
                        .HasColumnType("double precision");

                    b.Property<int>("MinTradingDays")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("PeakEquity")
                        .HasColumnType("numeric");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<double>("ProfitTargetPercent")
                        .HasColumnType("double precision");

                    b.Property<bool>("SingleStep")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("StartingBalance")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("TradingAccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("TradingDaysCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("TrailingLockThreshold")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TrailingThresholdAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("PropFirmChallenges");
                });

            modelBuilder.Entity("Core.PropRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoFlatten")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DailyLossLimit")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastFlattenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxConcurrentLiveInstances")
                        .HasColumnType("integer");

                    b.Property<double>("MaxDrawdownPercent")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("TradingAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TradingAccountId");

                    b.HasIndex("UserId", "TradingAccountId")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("PropRules");
                });

            modelBuilder.Entity("Core.TradingAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("AccountNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("Broker")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("CTidId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CtidTraderAccountId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("EncryptedToken")
                        .HasColumnType("bytea");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLive")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LinkMethod")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid?>("OpenApiAuthorizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CTidId", "AccountNumber")
                        .IsUnique();

                    b.ToTable("TradingAccounts");
                });

            modelBuilder.Entity("Core.ViewerGrant", b =>
                {
                    b.Property<Guid>("ViewerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GrantedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("ViewerId", "InstanceId");

                    b.HasIndex("InstanceId");

                    b.ToTable("ViewerGrants");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Core.AdminUser", b =>
                {
                    b.HasBaseType("Core.AppUser");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("Core.OwnerUser", b =>
                {
                    b.HasBaseType("Core.AppUser");

                    b.HasDiscriminator().HasValue("Owner");
                });

            modelBuilder.Entity("Core.RegularUser", b =>
                {
                    b.HasBaseType("Core.AppUser");

                    b.HasDiscriminator().HasValue("User");
                });

            modelBuilder.Entity("Core.ViewerUser", b =>
                {
                    b.HasBaseType("Core.AppUser");

                    b.Property<bool>("SeeAllInstances")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue("Viewer");
                });

            modelBuilder.Entity("Core.CSharpProject", b =>
                {
                    b.HasBaseType("Core.CBotSourceProject");

                    b.HasDiscriminator().HasValue("CSharp");
                });

            modelBuilder.Entity("Core.PythonProject", b =>
                {
                    b.HasBaseType("Core.CBotSourceProject");

                    b.HasDiscriminator().HasValue("Python");
                });

            modelBuilder.Entity("Core.CompletedBacktestInstance", b =>
                {
                    b.HasBaseType("Core.Instance");

                    b.Property<string>("BacktestSettingsJson")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text");

                    b.Property<string>("ContainerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ReportJson")
                        .HasColumnType("text");

                    b.Property<string>("ResultJsonPath")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StoppedAt")
                        .HasColumnType("timestamp with time zone");

                    b.ToTable("Instances", t =>
                        {
                            t.Property("ContainerId")
                                .HasColumnName("CompletedBacktestInstance_ContainerId");

                            t.Property("StartedAt")
                                .HasColumnName("CompletedBacktestInstance_StartedAt");

                            t.Property("StoppedAt")
                                .HasColumnName("CompletedBacktestInstance_StoppedAt");
                        });

                    b.HasDiscriminator().HasValue("BacktestCompleted");
                });

            modelBuilder.Entity("Core.FailedBacktestInstance", b =>
                {
                    b.HasBaseType("Core.Instance");

                    b.Property<string>("BacktestSettingsJson")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text");

                    b.Property<string>("ContainerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("StoppedAt")
                        .HasColumnType("timestamp with time zone");

                    b.ToTable("Instances", t =>
                        {
                            t.Property("ContainerId")
                                .HasColumnName("FailedBacktestInstance_ContainerId");

                            t.Property("FailureReason")
                                .HasColumnName("FailedBacktestInstance_FailureReason");

                            t.Property("StartedAt")
                                .HasColumnName("FailedBacktestInstance_StartedAt");

                            t.Property("StoppedAt")
                                .HasColumnName("FailedBacktestInstance_StoppedAt");
                        });

                    b.HasDiscriminator().HasValue("BacktestFailed");
                });

            modelBuilder.Entity("Core.FailedRunInstance", b =>
                {
                    b.HasBaseType("Core.Instance");

                    b.Property<string>("ContainerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("StoppedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasDiscriminator().HasValue("RunFailed");
                });

            modelBuilder.Entity("Core.PendingBacktestInstance", b =>
                {
                    b.HasBaseType("Core.Instance");

                    b.Property<string>("BacktestSettingsJson")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("BacktestPending");
                });

            modelBuilder.Entity("Core.PendingRunInstance", b =>
                {
                    b.HasBaseType("Core.Instance");

                    b.HasDiscriminator().HasValue("RunPending");
                });

            modelBuilder.Entity("Core.RunningBacktestInstance", b =>
                {
                    b.HasBaseType("Core.Instance");

                    b.Property<string>("BacktestSettingsJson")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text");

                    b.Property<string>("ContainerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.ToTable("Instances", t =>
                        {
                            t.Property("ContainerId")
                                .HasColumnName("RunningBacktestInstance_ContainerId");

                            t.Property("StartedAt")
                                .HasColumnName("RunningBacktestInstance_StartedAt");
                        });

                    b.HasDiscriminator().HasValue("BacktestRunning");
                });

            modelBuilder.Entity("Core.RunningRunInstance", b =>
                {
                    b.HasBaseType("Core.Instance");

                    b.Property<string>("ContainerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.ToTable("Instances", t =>
                        {
                            t.Property("ContainerId")
                                .HasColumnName("RunningRunInstance_ContainerId");

                            t.Property("StartedAt")
                                .HasColumnName("RunningRunInstance_StartedAt");
                        });

                    b.HasDiscriminator().HasValue("RunRunning");
                });

            modelBuilder.Entity("Core.ScheduledBacktestInstance", b =>
                {
                    b.HasBaseType("Core.Instance");

                    b.Property<string>("BacktestSettingsJson")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("BacktestScheduled");
                });

            modelBuilder.Entity("Core.ScheduledRunInstance", b =>
                {
                    b.HasBaseType("Core.Instance");

                    b.HasDiscriminator().HasValue("RunScheduled");
                });

            modelBuilder.Entity("Core.StartingBacktestInstance", b =>
                {
                    b.HasBaseType("Core.Instance");

                    b.Property<string>("BacktestSettingsJson")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text");

                    b.Property<string>("ContainerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.ToTable("Instances", t =>
                        {
                            t.Property("ContainerId")
                                .HasColumnName("StartingBacktestInstance_ContainerId");
                        });

                    b.HasDiscriminator().HasValue("BacktestStarting");
                });

            modelBuilder.Entity("Core.StartingRunInstance", b =>
                {
                    b.HasBaseType("Core.Instance");

                    b.Property<string>("ContainerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.ToTable("Instances", t =>
                        {
                            t.Property("ContainerId")
                                .HasColumnName("StartingRunInstance_ContainerId");
                        });

                    b.HasDiscriminator().HasValue("RunStarting");
                });

            modelBuilder.Entity("Core.StoppedRunInstance", b =>
                {
                    b.HasBaseType("Core.Instance");

                    b.Property<string>("ContainerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StoppedAt")
                        .HasColumnType("timestamp with time zone");

                    b.ToTable("Instances", t =>
                        {
                            t.Property("ContainerId")
                                .HasColumnName("StoppedRunInstance_ContainerId");

                            t.Property("StartedAt")
                                .HasColumnName("StoppedRunInstance_StartedAt");

                            t.Property("StoppedAt")
                                .HasColumnName("StoppedRunInstance_StoppedAt");
                        });

                    b.HasDiscriminator().HasValue("RunStopped");
                });

            modelBuilder.Entity("Core.StoppingBacktestInstance", b =>
                {
                    b.HasBaseType("Core.Instance");

                    b.Property<string>("BacktestSettingsJson")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text");

                    b.Property<string>("ContainerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.ToTable("Instances", t =>
                        {
                            t.Property("ContainerId")
                                .HasColumnName("StoppingBacktestInstance_ContainerId");

                            t.Property("StartedAt")
                                .HasColumnName("StoppingBacktestInstance_StartedAt");
                        });

                    b.HasDiscriminator().HasValue("BacktestStopping");
                });

            modelBuilder.Entity("Core.StoppingRunInstance", b =>
                {
                    b.HasBaseType("Core.Instance");

                    b.Property<string>("ContainerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.ToTable("Instances", t =>
                        {
                            t.Property("ContainerId")
                                .HasColumnName("StoppingRunInstance_ContainerId");

                            t.Property("StartedAt")
                                .HasColumnName("StoppingRunInstance_StartedAt");
                        });

                    b.HasDiscriminator().HasValue("RunStopping");
                });

            modelBuilder.Entity("Core.ActiveBacktestNode", b =>
                {
                    b.HasBaseType("Core.Node");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<byte[]>("EncryptedApiSecret")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bytea");

                    b.Property<bool>("IsReachable")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("timestamp with time zone");

                    b.HasDiscriminator().HasValue("ActiveBacktest");
                });

            modelBuilder.Entity("Core.ActiveMixedNode", b =>
                {
                    b.HasBaseType("Core.Node");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<byte[]>("EncryptedApiSecret")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bytea");

                    b.Property<bool>("IsReachable")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("timestamp with time zone");

                    b.HasDiscriminator().HasValue("ActiveMixed");
                });

            modelBuilder.Entity("Core.ActiveRunNode", b =>
                {
                    b.HasBaseType("Core.Node");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<byte[]>("EncryptedApiSecret")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bytea");

                    b.Property<bool>("IsReachable")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("timestamp with time zone");

                    b.HasDiscriminator().HasValue("ActiveRun");
                });

            modelBuilder.Entity("Core.DecommissioningNode", b =>
                {
                    b.HasBaseType("Core.Node");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<byte[]>("EncryptedApiSecret")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bytea");

                    b.Property<bool>("IsReachable")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("timestamp with time zone");

                    b.HasDiscriminator().HasValue("Decommissioning");
                });

            modelBuilder.Entity("Core.LocalNode", b =>
                {
                    b.HasBaseType("Core.Node");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue("Local");
                });

            modelBuilder.Entity("Core.OfflineNode", b =>
                {
                    b.HasBaseType("Core.Node");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<byte[]>("EncryptedApiSecret")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("bytea");

                    b.Property<bool>("IsReachable")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("timestamp with time zone");

                    b.HasDiscriminator().HasValue("Offline");
                });

            modelBuilder.Entity("Core.AgentMandate", b =>
                {
                    b.HasOne("Core.CBot", "CBot")
                        .WithMany()
                        .HasForeignKey("CBotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.TradingAccount", "TradingAccount")
                        .WithMany()
                        .HasForeignKey("TradingAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Core.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CBot");

                    b.Navigation("TradingAccount");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.AgentProposal", b =>
                {
                    b.HasOne("Core.AgentMandate", "Mandate")
                        .WithMany("Proposals")
                        .HasForeignKey("MandateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mandate");
                });

            modelBuilder.Entity("Core.AlertEvent", b =>
                {
                    b.HasOne("Core.AlertRule", "Rule")
                        .WithMany("Events")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("Core.AlertRule", b =>
                {
                    b.HasOne("Core.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.CBot", b =>
                {
                    b.HasOne("Core.CBotSourceProject", "SourceProject")
                        .WithMany()
                        .HasForeignKey("SourceProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Core.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceProject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.CBotSourceProject", b =>
                {
                    b.HasOne("Core.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.CTraderIdAccount", b =>
                {
                    b.HasOne("Core.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.ConsentRecord", b =>
                {
                    b.HasOne("Core.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.CopyDestination", b =>
                {
                    b.HasOne("Core.CopyProfile", null)
                        .WithMany("Destinations")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Core.CopySymbolFilter", "SymbolFilters", b1 =>
                        {
                            b1.Property<Guid>("CopyDestinationId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Symbol")
                                .IsRequired();

                            b1.HasKey("CopyDestinationId", "__synthesizedOrdinal");

                            b1.ToTable("CopyDestinations");

                            b1.ToJson("SymbolFilters");

                            b1.WithOwner()
                                .HasForeignKey("CopyDestinationId");
                        });

                    b.OwnsMany("Core.CopySymbolMapEntry", "SymbolMaps", b1 =>
                        {
                            b1.Property<Guid>("CopyDestinationId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Destination")
                                .IsRequired();

                            b1.Property<string>("Source")
                                .IsRequired();

                            b1.HasKey("CopyDestinationId", "__synthesizedOrdinal");

                            b1.ToTable("CopyDestinations");

                            b1.ToJson("SymbolMaps");

                            b1.WithOwner()
                                .HasForeignKey("CopyDestinationId");
                        });

                    b.Navigation("SymbolFilters");

                    b.Navigation("SymbolMaps");
                });

            modelBuilder.Entity("Core.CopyProfile", b =>
                {
                    b.HasOne("Core.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Instance", b =>
                {
                    b.HasOne("Core.CBot", "CBot")
                        .WithMany()
                        .HasForeignKey("CBotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Node", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId");

                    b.HasOne("Core.ParamSet", "ParamSet")
                        .WithMany()
                        .HasForeignKey("ParamSetId");

                    b.HasOne("Core.TradingAccount", "TradingAccount")
                        .WithMany()
                        .HasForeignKey("TradingAccountId");

                    b.HasOne("Core.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CBot");

                    b.Navigation("Node");

                    b.Navigation("ParamSet");

                    b.Navigation("TradingAccount");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.InstanceLog", b =>
                {
                    b.HasOne("Core.Instance", "Instance")
                        .WithMany()
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instance");
                });

            modelBuilder.Entity("Core.McpApiKey", b =>
                {
                    b.HasOne("Core.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.NodeStats", b =>
                {
                    b.HasOne("Core.Node", "Node")
                        .WithOne("LatestStats")
                        .HasForeignKey("Core.NodeStats", "NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("Core.OpenApiApplication", b =>
                {
                    b.HasOne("Core.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.OpenApiAuthorization", b =>
                {
                    b.HasOne("Core.OpenApiApplication", null)
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.ParamSet", b =>
                {
                    b.HasOne("Core.CBot", "CBot")
                        .WithMany("ParamSets")
                        .HasForeignKey("CBotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CBot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.PropFirmChallenge", b =>
                {
                    b.HasOne("Core.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.PropRule", b =>
                {
                    b.HasOne("Core.TradingAccount", "TradingAccount")
                        .WithMany()
                        .HasForeignKey("TradingAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradingAccount");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.TradingAccount", b =>
                {
                    b.HasOne("Core.CTraderIdAccount", "CTid")
                        .WithMany("TradingAccounts")
                        .HasForeignKey("CTidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CTid");
                });

            modelBuilder.Entity("Core.ViewerGrant", b =>
                {
                    b.HasOne("Core.Instance", "Instance")
                        .WithMany()
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.AppUser", "Viewer")
                        .WithMany()
                        .HasForeignKey("ViewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instance");

                    b.Navigation("Viewer");
                });

            modelBuilder.Entity("Core.AgentMandate", b =>
                {
                    b.Navigation("Proposals");
                });

            modelBuilder.Entity("Core.AlertRule", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Core.CBot", b =>
                {
                    b.Navigation("ParamSets");
                });

            modelBuilder.Entity("Core.CTraderIdAccount", b =>
                {
                    b.Navigation("TradingAccounts");
                });

            modelBuilder.Entity("Core.CopyProfile", b =>
                {
                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("Core.Node", b =>
                {
                    b.Navigation("LatestStats");
                });
#pragma warning restore 612, 618
        }
    }
}
